namespace GestVAEcls.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PieceJointesL1 : DbMigration
    {
        public override void Up()
        {
            System.Diagnostics.Trace.WriteLine(DateTime.Now.ToLongDateString() + ":[DBMIGRATION UP]" + "PieceJointesL1 " + "start");
            Sql("DELETE FROM [dbo].[PieceJointeItems]");
            Sql("DELETE FROM [dbo].[PieceJointeCategories]");
            Sql("SET IDENTITY_INSERT [dbo].[PieceJointeCategories] ON");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (3, N'L1', N'RUBRIQUE N°5', 1905-06-24, 1905-06-24, 0, NULL)");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (4, N'L1', N'RUBRIQUE N°6', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (5, N'L1', N'ATTESTATION D''ACTIVITES', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (6, N'L1', N'CA', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (7, N'L1', N'BULLETIN SALAIRE', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (8, N'L1', N'CARSAT', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (9, N'L1', N'Activités LIBERALES', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (10, N'L1', N'JUSTIFICATIF D''IDENTITE', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (11, N'L1', N'ENGAGEMENT PARCOURS', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (12, N'L1', N'AUTRES', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (15, N'L2', N'EMPLOI', 1905-06-24, 1905-06-24, 1, NULL)");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (16, N'L2', N'SI MOINS DE 3 ANS ET QU''IL Y AURA 3 ANS LE JOUR DU JURY', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (17, N'L2', N'CONSEIL D''ADMNISTRATION', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (18, N'L2', N'FORMATION DIPLOME', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (19, N'L2', N'DUREE', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (20, N'L2', N'SOMMAIRE', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (21, N'L2', N'SIGNATURE', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (22, N'L2', N'RUBRIQUES', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (23, N'L2', N'SYNTHESE', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (24, N'L2', N'ANNEXES', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (25, N'L2', N'2EME PASSAGE', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeCategories] ([ID], [Livret], [Categorie], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (26, N'L2', N'ENGAGEMENT PARCOURS', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("SET IDENTITY_INSERT [dbo].[PieceJointeCategories] OFF");

            Sql("SET IDENTITY_INSERT [dbo].[PieceJointeItems] ON");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (1, 3, N'La rubrique N° 5 complétée: dans la colonne6, indiquez la date de début et de fin, dans la colonne8, détaillez le cumul des heures effectuées; dans la colonne 9, détaillez vos activités en lien direct avec le référentiel d''activités du CAFDES, joindre ce détail sur une ou plusieurs feuilles annexes;', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (4, 4, N'La rubrique N°6 : la déclaration sur l''honneur dûment comlpétée, signée et datée;', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (5, 5, N'Votre attestation d''activités salariées complétée de tous les items surlignés en jaune, à faire remplir par votre employeur', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (55, 5, N'Votre attestation d''activités salariées dûment complétée du nombre total d''heures effectuées, à faire remplir par votre employeur', 2019-05-06, 2019-05-06, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (56, 5, N'Votre attestation d''activités salariées complétée de l''adresse de l''entreprise ou de l''employeur, du cachet de l''établissement ou de l''association, datée et signée.', 2019-05-06, 2019-05-06, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (57, 5, N'Votre attestation d''activités bénévoles complétée du nom, prénom et fonction du deuxième stagiaire', 2019-05-06, 2019-05-06, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (6, 6, N'La copie du compte-rendu du conseil d''Administration attestant votre élection au sein du bureau en tant que Président de l''association.', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (9, 7, N'Copie des bulletins de salaires ceux du : ...', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (11, 8, N'Un rélévé de carière à demander à la CARSAT édition 2019', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (12, 9, N'Copie extrait Kbis;', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (13, 10, N'La copie recto-verso de votre carte d''identité ou de votre passeport;', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (20, 11, N'Votre convention (entre vous, l''employeur et l''EHESP en 3 exemplaires) ou contrat (entre vous et l''EHESP en 2 exemplaires) relatif à un parcours de validation des acquis de l''expérience dûment complété et signé. En cas de prise en charge par un organisme financeur, l''EHESP n''accepte pas la subrogation. Par conséquent, les frais sont à prendre en charge par l''employeur qui sera ensuite remboursé par l''organisme financeur.', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (28, 15, N'Une justification de votre emploi actuel', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (29, 15, N'Les copies justifiant des emplois et activités bénévoles mentionnés en page 7 et 8 (certificats de travail et/ou attestations)', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (30, 15, N'De plus l''expérience que vous avez choisi datant de plus de 10 ans, ne peut pas être l''unique expérience de travail développée', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (31, 16, N'Au (date des ans), une attestation signée de votre employeur indiquant que vous êtes toujours en poste', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (32, 17, N'La copie du compte rendu du conseil d''administration attestant de votre élection au sein du bureau en tant que président de l''association(nom de l''association)', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (33, 18, N'Le relevé de parcours de formation au sein du groupe COMPASS', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (34, 18, N'La copie de votre diplome CAFERUIS', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (35, 18, N'La copie des diplômes et/ou certificats des formations', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (36, 19, N'La description d''une seconde expérience car l''expérience qui constitue votre Livret2 à ce jour ne permet pas de justifier d''au moins 3 années d''activités équivalent Temps plein (voir page 10 de la notice d''accompagnement pour remplir le Livret2)', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (37, 19, N'Si vous ne souhaitez pas développer une seconde expérience, vous voudrez bien fournir une attestation sur l''honneur mentionnant au jury vôtre choix de ne développer qu''une seule expérience qui concerne éventuellement les expériences précédentes', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (38, 20, N'Le sommaire de votre livret de présentation des acquis de l''expérience.', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (39, 21, N'La signature originale de l''attestation sur l''honneur  et de la demande d''inscription en vue de l''obtention du CAFDES (voir Page 5 du Livret 2)', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (40, 22, N'La page explicative du livret2 où figure un cadre sur votre identitié à compléter ainsi qu''un cadre réservé à l''administration', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (41, 22, N'La page de couverture complétée de votre nom, prénom et numéro de dossier', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (42, 22, N'Le tableau rubrique 2 (vos expériences salariées) dûment complété', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (43, 22, N'Le tableau rubrique 3 (votre parcours de formation) dûment complété', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (44, 22, N'Le point 4.1.1 : Votre emploi ou votre fonction bénévole dûment complété', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (45, 22, N'Le point 4.2.4 : votre quatrième situation de travail (gestion économique, financière et logistique d''un établissement ou d''un service)', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (46, 22, N'Le point 5.3 : Analyse globale de votre expérience n° 2', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (47, 23, N'Le tableau de synthèse des documents annexes', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (48, 23, N'Le tableau de synthèse des documents annexes dûment complété des fonction en lien avec les annexes', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (49, 24, N'Vos annexes en français dûment traduites en français par un traducteur assermenté', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (50, 24, N'Vos certificats de travail ou attestations non anonymisés', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (51, 24, N'4 exemplaires supplémentaires de l''ensemble des annexes', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (52, 25, N'La copie de relevé de décision de jury', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (53, 25, N'La copie du dernier relevé de décision de jury qui vous a été adressé', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("INSERT INTO [dbo].[PieceJointeItems] ([ID], [Categorie_ID], [Libelle], [dateCreation], [dateModif], [bDeleted], [AttSup]) VALUES (54, 26, N'Votre convention ou contrat relatif à un parcours de validation des acquis de l''expérience dûment complété et signé (en 3 exemplaires)', 1905-06-24, 1905-06-24, 0, N'')");
            Sql("SET IDENTITY_INSERT [dbo].[PieceJointeItems] OFF");
            System.Diagnostics.Trace.WriteLine(DateTime.Now.ToLongDateString() + ":[DBMIGRATION UP]" + "PieceJointesL1 " + "End");
        }

        public override void Down()
        {
            System.Diagnostics.Trace.WriteLine(DateTime.Now.ToLongDateString() + ":[DBMIGRATION DOWN]" + "PieceJointesL1 " + "start");
            System.Diagnostics.Trace.WriteLine(DateTime.Now.ToLongDateString() + ":[DBMIGRATION DOWN]" + "PieceJointesL1 " + "End");
        }
    }
}
