// <auto-generated />
namespace GestVAEcls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BG001017Mail3SituationParticuliere : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BG001017Mail3SituationParticuliere));
        
        string IMigrationMetadata.Id
        {
            get { return "201909060829229_BG001017 Mail3-SituationParticuliere"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
