// <auto-generated />
namespace GestVAEcls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class L2DateRecept2emeRetour : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(L2DateRecept2emeRetour));
        
        string IMigrationMetadata.Id
        {
            get { return "201905141347385_L2DateRecept2emeRetour"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
