// <auto-generated />
namespace GestVAEcls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class supprT1T2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(supprT1T2));
        
        string IMigrationMetadata.Id
        {
            get { return "201901030725272_supprT1T2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
