// <auto-generated />
namespace GestVAEcls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RecoursLivret : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RecoursLivret));
        
        string IMigrationMetadata.Id
        {
            get { return "201901101010442_Recours-Livret"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
