// <auto-generated />
namespace GestVAEcls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class V20190901 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V20190901));
        
        string IMigrationMetadata.Id
        {
            get { return "201909061011499_V20190901"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
