// <auto-generated />
namespace GestVAEcls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CandTypeDemande : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CandTypeDemande));
        
        string IMigrationMetadata.Id
        {
            get { return "202001211530547_CandTypeDemande"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
