//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEF6
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;

    public partial class T1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T1()
        {
            this.T2s = new ObservableCollection<T2>();
            dateCreation = DateTime.Now;
            dateModif = DateTime.Now;
        }

        public int ID { get; set; }
        public System.DateTime dateCreation { get; set; }
        public System.DateTime dateModif { get; set; }
        public bool bDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<T2> T2s { get; set; }
    }
}
