//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T2
    {

        public T2()
        {
            dateCreation = DateTime.Now;
            dateModif = DateTime.Now;

        }
        public int ID { get; set; }
        public System.DateTime dateCreation { get; set; }
        public System.DateTime dateModif { get; set; }
        public bool bDeleted { get; set; }
        public int T1ID1 { get; set; }
    
        public virtual T1 T1ID { get; set; }
    }
}
