SELECT        '' as '5.1', '' as '5.2', '' as '5.3', 'PAR_ADMISSION' as '5.4', 'false' as '5.5',
			r.DateJury as '5.6', r.dateJury as '5.7', 'EN_PRESENTIEL' as '5.8', '35000' as '5.9',
			r.dateNotificationJury as '5.10', r.DateValidite as '5.11',
			'' as '5.12', '' as '5.13', '' as '5.14', 'nil' as '5.15', 'SANS_MENTION' as '5.16', '' as '5.17',
			'' as '6.1', '' as '6.2', '' as '6.3', '' as '6.4',
			'VAE' as '7.1', 'VAE_CLASSIQUE' as '7.2', 'CERTIFIE' as '7.3', r.DateReceptEHESPComplet as '7.4',
			iif(r.NomJeuneFille is null,r.nom, r.NomJeuneFille) as '8.1', 
			r.nom as '8.2',
			r.Prenom as '8.3',
			r.Prenom2 as '8.4',
			r.Prenom3 as '8.5',
			Year(r.DateNaissance) as '8.6',
			month(r.DateNaissance) as '8.7',
			DAY(r.DateNaissance) as '8.8',
			r.sexe AS '8.9',
			candidats.INSEECommuneNaissance as '8.10',
			candidats.CPNaissance as '8.11',
			r.VilleNaissance as '8.12',
			Candidats.INSEEPaysNaissance as '8.13',
			r.PaysNaissance as '8.14',
			'' as '9.1',
			'' as '9.2',
			'' as '9.3' 
FROM            RQ_L2_DOC r inner join Candidats on r.ID = Candidats.ID
