//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int Id { get; set; }
        public string ProductShortName { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string BarCode { get; set; }
        public Nullable<decimal> PricePer { get; set; }
    
        public virtual ICollection<OrderLine> OrderLines { get; set; }
    }
}
